### ISSUE TITLE
API paths differ from docs

### ISSUE THREAD

**Issue by tarasyarema** [recurly/recurly-client-go#79]
Was working on some integration tests and found out that the requested path from `ListAccounts` is `/accounts` and not `/sites.{siteId}/accounts` as it says in the docs and the OpenAPI reference.

Wanted to know how to handle this, as we are trying to implement integration tests using an external mocker (so that we do not need the whole `ClientInterface`). As a side note, the `HTTPCaller.Call` interface has an unexported parameter type, so I guess that cannot be used to mock, as we do not have the type available...

References:
[1] `client.ListAccounts`: https://github.com/recurly/recurly-client-go/blob/7281b1a215a4935e9274891b46191ffcd21db5af/client_operations.go#L578
[2] Docs to Accounts: https://developers.recurly.com/api/v2019-10-10/index.html#operation/list_accounts

**Comment by douglasmiller** [comment]
@tarasyarema, I apologize for the delayed response to your inquiry.

As you've pointed out, the `/sites/{site_id}` prefix is not required for the API endpoints. Recurly API will infer the required `site_id` from the private API key that is used when making requests. The client libraries do not include this in the operations in order to remove the need for the `site_id` to be specified for each request. We are considering removing this from the candidate version of the openapi specification, currently called `v2020-01-01`. 

As for how to handle this in your external mocker, I'm not 100% certain as I don't know what you're using exactly. If it is a self developed mocker, you could strip the prefix (excluding the `get_site` endpoint `/sites/{site_id}`)

We will get that `optionsApplier` to be exported. Sorry about that.

**Comment by tarasyarema** [comment]
1. Ok, could not find why the `site_id` was missing. Thanks for the explanation.
2. In the end as we could not mock it because of the unexported struct, we had a proxy approach, which seems to be working fine.

Closing the PR, thanks!
